[project]
name = "flyte-ml-demo"
version = "0.1.0"
description = "My Flyte demo project pulling image from my DockerHub"
readme = "README.md"
requires-python = ">=3.9,<3.13"
dependencies = [
    "flytekit",
    "pandas",
    "numpy",
    "scikit-learn",
    "pyarrow",
    "fastparquet"
]